import type { Metadata } from "next";
import { Karla } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import SideBar from "./components/sidebar";
import PageWrapper from "./components/pagewrapper";

const karla = Karla({
  weight:["200","300","400","600","700","800"],
  subsets:['latin'],
  variable:"--font-karla"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={karla.className}>
        
        <SideBar>

        </SideBar>
        <Header>

        </Header>
        <PageWrapper>
        {children}
        </PageWrapper>
      </body>
    </html>
  );
}
